=== Pandrex247/jakartaee-tck-tools/docs/dtd/cts-web-page/webpage.dtd
<?xml version='1.0' encoding='UTF-8' ?>

<!--Generated by Turbo XML 2.3.0.100.-->
<!--

    Copyright (c) 2002, 2018 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

-->
<!--                                                                          -->
<!--                                                                          -->
<!-- This DTD defines a CTS web page.  The idea is to allow CTS developers    -->
<!-- to place web content in an XML file that adheres to this DTD and use an  -->
<!-- automated tool to generate web pages from the XML file.  This will       -->
<!-- allow CTS developers to simply place there content in the XML file and   -->
<!-- and not worry about the presentation of the content.  It should also     -->
<!-- ease the development of CTS web pages since adding content to an XML     -->
<!-- file is well defined.  This approach should also assist in the creation  -->
<!-- of a consistent web site where all the pages adhere to a well-defined    -->
<!-- presentation.                                                            -->
<!--                                                                          -->
<!-- Features to add:                                                         -->
<!--   4.A framed view, this is the right frame, link list for left frame     -->
<!--                                                                          -->

<!ENTITY % position "LEFT | RIGHT | CENTER">
<!ENTITY % boolean "TRUE | FALSE">

<!ELEMENT webpage  (introduction? , sections? , footer?)>
<!ATTLIST webpage  title CDATA  #REQUIRED >

<!ELEMENT introduction (#PCDATA | link | mail)*>

<!ELEMENT sections (section | list | table | image)*>

<!ELEMENT section  (sub-section+)>
<!ATTLIST section  title CDATA  #REQUIRED >

<!ELEMENT sub-section (#PCDATA | link | mail)*>

<!ELEMENT mail  (#PCDATA)>
<!ATTLIST mail  url CDATA  #REQUIRED >

<!ELEMENT footer (#PCDATA | mail | link)*>

<!ELEMENT list  (list-element*)>
<!ATTLIST list  title     CDATA        #REQUIRED
                numbered  (%boolean;)  #REQUIRED >

<!ELEMENT list-element (#PCDATA | link | mail)*>

<!ELEMENT table  (col-label+ , row-data*)>
<!ATTLIST table  title CDATA  #REQUIRED
                 row-labels (%boolean;) #REQUIRED>

<!ELEMENT col-label (#PCDATA)>

<!ELEMENT row-data (row-element*)>
<!ATTLIST row-data label     CDATA       #IMPLIED>

<!ELEMENT image EMPTY>
<!ATTLIST image title     CDATA         #REQUIRED
                url       CDATA         #REQUIRED
                position  (%position;)  #REQUIRED >

<!ELEMENT row-element (#PCDATA)>

<!ELEMENT link  (#PCDATA)>
<!ATTLIST link  url CDATA  #REQUIRED >

<!ELEMENT url  (#PCDATA)>

=== Pandrex247/jakartaee-tck-tools/docs/dtd/cts-web-page/cts-example.xml
<?xml version = "1.0" encoding = "UTF-8"?>
<!DOCTYPE webpage SYSTEM "http://invalid.domain.com/testCTS/libs/DTDs/webpage.dtd">
<!--

    Copyright (c) 2018 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

-->

<webpage title = "CTS Example Web Page">
	<introduction>This web page is an example of what a CTS web
		page may look like.  This is the example introduction section.
		The quick brown fox jumped over the lazy dog.  The quick brown
		fox jumped over the lazy dog.  All work and no play makes Jack
		a dull boy.  Got to <link url="http://www.espn.com">ESPN.com</link>
		to receive your prize.
	</introduction>
	<sections>
		<section title = "Documents">
			<sub-section>
				This is an example of a sub-section within the 
				documents section.  This element can contain mixed
				content.  Meaning this element can contain PCDATA
				as well as url elements.  Here is a nested link element
				that points to
				<link url="http://www.sun.com">Sun's web site</link>.
			</sub-section>
			<sub-section>
				This is an example of another sub-section within the 
				documents section.
			</sub-section>
		</section>
		<section title = "Presentations">
			<sub-section>
				This is an example of a sub-section within the 
				documents section.  This element can contain mixed
				content.  Meaning this element can contain PCDATA
				as well as url elements.  Here is a nested link element
				that points to
				<link url="http://www.sun.com">Sun's web site</link>.
			</sub-section>
		</section>
		<list title="List 1" numbered="FALSE">
		  <list-element>
		    List item 1
		  </list-element>
		  <list-element>
		    List item 2
		  </list-element>
		  <list-element>
		    List item 3 is a link to
		    <link url="http://www.sun.com">Sun's web page</link>
		  </list-element>
		</list>
		<image title="Picture 1"
		       url="file:///D:/Download/cts-web-page/maya.jpg"
		       position="CENTER"/>
		<table title="Table 1 Title" row-labels="FALSE">
		  <col-label>Column 1</col-label>
		  <col-label>Column 2</col-label>
		  <col-label>Column 3</col-label>
		  <col-label>Column 4</col-label>
		  <row-data label="Row 1">
		    <row-element>Value 1.1</row-element>
		    <row-element>Value 2.1</row-element>
		    <row-element>Value 3.1</row-element>
		    <row-element>Value 4.1</row-element>
		  </row-data>
		  <row-data label="Row 2">
		    <row-element>Value 1.2</row-element>
		    <row-element>Value 2.2</row-element>
		    <row-element>Value 3.2</row-element>
		    <row-element>Value 4.2</row-element>
		  </row-data>
		  <row-data label="Row 3">
		    <row-element>Value 1.3</row-element>
		    <row-element>Value 2.3</row-element>
		    <row-element>Value 3.3</row-element>
		    <row-element>Value 4.3</row-element>
		  </row-data>
		</table>
	</sections>
	<footer>
		This web page created by the CTS group.
	</footer>
</webpage>
